services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hs
      POSTGRES_PASSWORD: password
      POSTGRES_DB: handsup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

