# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summarizer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'summarizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10summarizer.proto\x12\x03gen\"B\n\x14\x43reateMessageRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\"&\n\x15\x43reateMessageResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t2[\n\x11SummarizerService\x12\x46\n\rCreateMessage\x12\x19.gen.CreateMessageRequest\x1a\x1a.gen.CreateMessageResponseB\x07Z\x05./genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summarizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./gen'
  _globals['_CREATEMESSAGEREQUEST']._serialized_start=25
  _globals['_CREATEMESSAGEREQUEST']._serialized_end=91
  _globals['_CREATEMESSAGERESPONSE']._serialized_start=93
  _globals['_CREATEMESSAGERESPONSE']._serialized_end=131
  _globals['_SUMMARIZERSERVICE']._serialized_start=133
  _globals['_SUMMARIZERSERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
